name: Publish project website

on:
  push:
    branches: main

jobs:
  deploy-website:
    name: Deploy MkDocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: .github/workflows/mkdocs_requirements.txt
          CUSTOM_DOMAIN: layerscaffold.appsoluut.app
